# Generated by Django 2.0.3 on 2018-03-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_line', models.CharField(max_length=150, verbose_name='nome linha')),
                ('numer_line', models.IntegerField(verbose_name='Numero da linha')),
                ('numer_car', models.CharField(max_length=5, verbose_name='numero carro')),
            ],
            options={
                'verbose_name': 'Veicles',
                'verbose_name_plural': 'Veicles',
            },
        ),
    ]
