# Generated by Django 2.0.3 on 2018-03-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veicle',
            options={'verbose_name': 'Veicle', 'verbose_name_plural': 'Veicles'},
        ),
    ]
