# Generated by Django 2.0.3 on 2018-03-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_auto_20180313_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mounth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('hours_entry', models.TimeField()),
                ('hours_exit', models.TimeField()),
                ('total_hours', models.CharField(max_length=8)),
                ('veicle', models.ForeignKey(on_delete='cascate', to='driver.Veicle')),
            ],
        ),
    ]
