# Generated by Django 2.0.3 on 2018-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('hours_entry', models.TimeField()),
                ('hours_exit', models.TimeField()),
                ('period_hour_entry', models.TimeField()),
                ('period_hour_exit', models.TimeField()),
                ('total_hours', models.TimeField(blank=True, null=True)),
                ('veicle', models.ForeignKey(on_delete='cascate', to='driver.Veicle')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
            },
        ),
    ]
