# Generated by Django 2.0.3 on 2018-03-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='total_hours',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
